### ISSUE TITLE
only linux ?

### ISSUE THREAD

**Issue by gedw99** [CanonicalLtd/go-dqlite#21]
seems this uses libuv. SO no mac no windows ?

**Comment by freeekanayaka** [comment]
libuv is supported on mac and windows. However the part of dqlite that uses Go is being ported to C, and will use [libraft](https://github.com/CanonicalLtd/raft), which uses libuv + the linux AIO APIs. It should not be difficult to add support for mac and windows on libraft, if there are use cases for that.

**Comment by gedw99** [comment]
Will I still be able to use it from golang though ?  You will use cgo ?

**Comment by freeekanayaka** [comment]
Sorry, I didn't notice you had re-opened this issue.

The work to port all Go-bits for dqlite to C has been finished. You can still use dqlite from Go via the go-dqlite bindings. From Go's point of view the change was mostly transparent.
